#!/bin/bash

# TODO: Same script for windows in each session?

log() {
    echo "$1"
    echo "-----"
}

current_session="$(tmux list-sessions | grep attached | sed 's/:.*//')"
current_window="$(tmux list-windows | grep active | sed 's/:.*//')"
session_window="$current_session:$current_window"

if [ -z $1 ]
then
    tmux neww "tmux ls | sed 's/:.*//' | fzf \
        --bind \"ctrl-n:execute(fzftree a)\" \
        --bind \"ctrl-n:+reload(tmux ls | sed 's/:.*//')\" \
        --bind \"ctrl-d:execute(fzftree d {})\" \
        --bind \"ctrl-d:+reload(tmux ls | sed 's/:.*//')+clear-query\" \
        --bind \"ctrl-m:execute(fzftree e {})\" \
        --bind \"ctrl-r:execute(fzftree r {})\" \
        --bind \"ctrl-r:+reload(tmux ls | sed 's/:.*//')+clear-query\" \
        "
else
    case $1 in
        d)
            tmux kill-session -t $2
            log "Session '$2' deleted"
            ;;
        a)
            read -p "Session name: " name

            if [ ! -z $name ]
            then
                tmux new-session -d -s $name
                log "Session '$name' created"
            fi
            ;;
        e)
            tmux switch -t $2
            tmux kill-window -t $session_window
            ;;
        r)
            read -p "Renaming session $2.`echo $'\nNew name: '`" name
            if [ ! -z $name ]; then
                tmux rename-session -t $2 $name
                log "Rename '$2' -> '$name'"; sleep 0.5
            fi
            ;;
        *)
            log "Exit"
            exit 1
            ;;
    esac
fi
